// ============================================
// features/trading/pnl/columns.ts
// ============================================

import { ColumnDef } from '@/components/ui/DataGrid';
import type { EquityPnLPosition, ETFPnLPosition, FXPnLPosition, BondPnLPosition } from './types';

// Equity P&L Columns
export const EQUITY_PNL_COLUMNS: ColumnDef<EquityPnLPosition>[] = [
  {
    id: 'symbol',
    header: 'Symbol',
    accessor: 'symbol',
    width: 90,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 150,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'quantity',
    header: 'Qty',
    accessor: 'quantity',
    width: 80,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'avgCost',
    header: 'Avg Cost',
    accessor: 'avgCost',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'lastPrice',
    header: 'Last',
    accessor: 'lastPrice',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'costBasis',
    header: 'Cost Basis',
    accessor: (row) => row.costBasis.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'marketValue',
    header: 'Mkt Value',
    accessor: (row) => row.marketValue.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPnL',
    header: 'Unreal P&L',
    accessor: (row) => row.unrealizedPnL.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPercent',
    header: 'Unreal %',
    accessor: 'unrealizedPercent',
    width: 85,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'realizedPnL',
    header: 'Real P&L',
    accessor: (row) => row.realizedPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'totalPnL',
    header: 'Total P&L',
    accessor: (row) => row.totalPnL.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnL',
    header: 'Day P&L',
    accessor: (row) => row.dayPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnLPercent',
    header: 'Day %',
    accessor: 'dayPnLPercent',
    width: 75,
    sortable: true,
    alignment: 'right',
  },
];

// ETF P&L Columns
export const ETF_PNL_COLUMNS: ColumnDef<ETFPnLPosition>[] = [
  {
    id: 'symbol',
    header: 'Symbol',
    accessor: 'symbol',
    width: 90,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 150,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'units',
    header: 'Units',
    accessor: 'units',
    width: 80,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'avgCost',
    header: 'Avg Cost',
    accessor: 'avgCost',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'lastPrice',
    header: 'Last',
    accessor: 'lastPrice',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'costBasis',
    header: 'Cost Basis',
    accessor: (row) => row.costBasis.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'marketValue',
    header: 'Mkt Value',
    accessor: (row) => row.marketValue.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPnL',
    header: 'Unreal P&L',
    accessor: (row) => row.unrealizedPnL.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPercent',
    header: 'Unreal %',
    accessor: 'unrealizedPercent',
    width: 85,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'totalPnL',
    header: 'Total P&L',
    accessor: (row) => row.totalPnL.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnL',
    header: 'Day P&L',
    accessor: (row) => row.dayPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnLPercent',
    header: 'Day %',
    accessor: 'dayPnLPercent',
    width: 75,
    sortable: true,
    alignment: 'right',
  },
];

// FX P&L Columns
export const FX_PNL_COLUMNS: ColumnDef<FXPnLPosition>[] = [
  {
    id: 'ccyPair',
    header: 'Pair',
    accessor: 'ccyPair',
    width: 85,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'direction',
    header: 'Dir',
    accessor: 'direction',
    width: 60,
    sortable: true,
    alignment: 'center',
  },
  {
    id: 'notional',
    header: 'Notional',
    accessor: 'notional',
    width: 120,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'avgRate',
    header: 'Avg Rate',
    accessor: 'avgRate',
    width: 95,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spotRate',
    header: 'Spot',
    accessor: 'spotRate',
    width: 95,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'ratePnLPips',
    header: 'P&L (pips)',
    accessor: 'ratePnLPips',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spotPnL',
    header: 'Spot P&L',
    accessor: (row) => row.spotPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'forwardPointsPnL',
    header: 'Fwd Pts P&L',
    accessor: (row) => row.forwardPointsPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPnL',
    header: 'Unreal P&L',
    accessor: (row) => row.unrealizedPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'realizedPnL',
    header: 'Real P&L',
    accessor: (row) => row.realizedPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'totalPnL',
    header: 'Total P&L',
    accessor: (row) => row.totalPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnL',
    header: 'Day P&L',
    accessor: (row) => row.dayPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayPnLPercent',
    header: 'Day %',
    accessor: 'dayPnLPercent',
    width: 75,
    sortable: true,
    alignment: 'right',
  },
];

// Bond P&L Columns
export const BOND_PNL_COLUMNS: ColumnDef<BondPnLPosition>[] = [
  {
    id: 'isin',
    header: 'ISIN',
    accessor: 'isin',
    width: 120,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 150,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'faceValue',
    header: 'Face Value',
    accessor: 'faceValue',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'avgPrice',
    header: 'Avg Price',
    accessor: 'avgPrice',
    width: 85,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'cleanPrice',
    header: 'Clean',
    accessor: 'cleanPrice',
    width: 85,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'pricePnL',
    header: 'Price P&L',
    accessor: (row) => row.pricePnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'couponReceived',
    header: 'Coupon',
    accessor: (row) => row.couponReceived.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'accruedPnL',
    header: 'Accrued',
    accessor: (row) => row.accruedPnL.amount,
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'rollPnL',
    header: 'Roll/Carry',
    accessor: (row) => row.rollPnL.amount,
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'unrealizedPnL',
    header: 'Unreal P&L',
    accessor: (row) => row.unrealizedPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'realizedPnL',
    header: 'Real P&L',
    accessor: (row) => row.realizedPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'totalPnL',
    header: 'Total P&L',
    accessor: (row) => row.totalPnL.amount,
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dayChangeBps',
    header: 'Day (bps)',
    accessor: 'dayChangeBps',
    width: 85,
    sortable: true,
    alignment: 'right',
  },
];
