// ============================================
// features/trading/liquidity/columns.ts
// ============================================

import { ColumnDef } from '@/components/ui/DataGrid';
import type {
  EquityLiquidityPosition,
  ETFLiquidityPosition,
  FXLiquidityPosition,
  BondLiquidityPosition,
} from './types';

// Equity Liquidity Columns
export const EQUITY_LIQUIDITY_COLUMNS: ColumnDef<EquityLiquidityPosition>[] = [
  {
    id: 'symbol',
    header: 'Symbol',
    accessor: 'symbol',
    width: 90,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 140,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'quantity',
    header: 'Quantity',
    accessor: 'quantity',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'marketValue',
    header: 'Mkt Value',
    accessor: (row) => row.marketValue.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'adv20d',
    header: 'ADV (20D)',
    accessor: 'adv20d',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'advValue',
    header: 'ADV Value',
    accessor: 'advValue',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'positionPctVolume',
    header: 'Pos % ADV',
    accessor: 'positionPctVolume',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'daysToLiquidate',
    header: 'Days to Liq',
    accessor: 'daysToLiquidate',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'bidAskSpreadBps',
    header: 'Spread (bps)',
    accessor: 'bidAskSpreadBps',
    width: 95,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spreadCost',
    header: 'Spread Cost',
    accessor: 'spreadCost',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'liquidityScore',
    header: 'Score',
    accessor: 'liquidityScore',
    width: 80,
    sortable: true,
    alignment: 'center',
  },
];

// ETF Liquidity Columns
export const ETF_LIQUIDITY_COLUMNS: ColumnDef<ETFLiquidityPosition>[] = [
  {
    id: 'symbol',
    header: 'Symbol',
    accessor: 'symbol',
    width: 90,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 140,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'units',
    header: 'Units',
    accessor: 'units',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'marketValue',
    header: 'Mkt Value',
    accessor: (row) => row.marketValue.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'adv20d',
    header: 'ADV (20D)',
    accessor: 'adv20d',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'positionPctVolume',
    header: 'Pos % ADV',
    accessor: 'positionPctVolume',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'daysToLiquidate',
    header: 'Days to Liq',
    accessor: 'daysToLiquidate',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'bidAskSpreadBps',
    header: 'Spread (bps)',
    accessor: 'bidAskSpreadBps',
    width: 95,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'premiumDiscount',
    header: 'Prem/Disc',
    accessor: 'premiumDiscount',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'aum',
    header: 'AUM',
    accessor: 'aum',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'liquidityScore',
    header: 'Score',
    accessor: 'liquidityScore',
    width: 80,
    sortable: true,
    alignment: 'center',
  },
];

// FX Liquidity Columns
export const FX_LIQUIDITY_COLUMNS: ColumnDef<FXLiquidityPosition>[] = [
  {
    id: 'ccyPair',
    header: 'Pair',
    accessor: 'ccyPair',
    width: 85,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'notional',
    header: 'Notional',
    accessor: 'notional',
    width: 120,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dailyVolumeEst',
    header: 'Daily Vol (Est)',
    accessor: 'dailyVolumeEst',
    width: 120,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'positionPctVolume',
    header: 'Pos % Vol',
    accessor: 'positionPctVolume',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spreadPips',
    header: 'Spread (pips)',
    accessor: 'spreadPips',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spreadCost',
    header: 'Spread Cost',
    accessor: 'spreadCost',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'timeToExecute',
    header: 'Time to Exec',
    accessor: 'timeToExecute',
    width: 100,
    sortable: true,
    alignment: 'center',
  },
  {
    id: 'marketHours',
    header: 'Mkt Hours',
    accessor: 'marketHours',
    width: 90,
    sortable: true,
    alignment: 'center',
  },
  {
    id: 'liquidityScore',
    header: 'Score',
    accessor: 'liquidityScore',
    width: 80,
    sortable: true,
    alignment: 'center',
  },
];

// Bond Liquidity Columns
export const BOND_LIQUIDITY_COLUMNS: ColumnDef<BondLiquidityPosition>[] = [
  {
    id: 'isin',
    header: 'ISIN',
    accessor: 'isin',
    width: 120,
    sortable: true,
    pinned: 'left',
    alignment: 'left',
  },
  {
    id: 'name',
    header: 'Name',
    accessor: 'name',
    width: 140,
    sortable: true,
    alignment: 'left',
  },
  {
    id: 'faceValue',
    header: 'Face Value',
    accessor: 'faceValue',
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'marketValue',
    header: 'Mkt Value',
    accessor: (row) => row.marketValue.amount,
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'estDailyVolume',
    header: 'Est Daily Vol',
    accessor: 'estDailyVolume',
    width: 110,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'positionPctVolume',
    header: 'Pos % Vol',
    accessor: 'positionPctVolume',
    width: 90,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'bidAskSpreadBps',
    header: 'Spread (bps)',
    accessor: 'bidAskSpreadBps',
    width: 95,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'spreadCost',
    header: 'Spread Cost',
    accessor: 'spreadCost',
    width: 100,
    sortable: true,
    alignment: 'right',
  },
  {
    id: 'dealerCount',
    header: 'Dealers',
    accessor: 'dealerCount',
    width: 75,
    sortable: true,
    alignment: 'center',
  },
  {
    id: 'lastTradeDate',
    header: 'Last Trade',
    accessor: 'lastTradeDate',
    width: 95,
    sortable: true,
    alignment: 'center',
  },
  {
    id: 'liquidityScore',
    header: 'Score',
    accessor: 'liquidityScore',
    width: 80,
    sortable: true,
    alignment: 'center',
  },
];
